services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sky_global_assets_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sky_global_assets_project.settings
      - key: PYTHON_VERSION
        value: 3.11
